'use client';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';
import Navbar from './(components)/Navbar';
import GetInTouch from './(components)/GetInTouch';
import Footer from './(components)/Footer';
import './globals.css';
import 'aos/dist/aos.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Scrollup from './(components)/scrollup';
import { UserProvider } from '@/lib/context/userContext';
import ToastProvider from './(components)/ToastProvider';
import useWebSocket from '@/lib/useWebSocket';

const inter = Inter({ subsets: ['latin'] });

function WebSocketHandler() {
  useWebSocket();
  return null;
}

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isLoginPage = pathname === '/login';

  return (
    <html lang="en">
      <head>
        <title>wishgeekstechserve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/wishi.svg" sizes="any" />
      </head>
      <body className={inter.className}>
        <ToastProvider>
          <UserProvider>
            {!isLoginPage && <Navbar />}
            {children}
            <Scrollup />
            {!isLoginPage && <GetInTouch />}
            {!isLoginPage && <Footer />}
            {/* Call useWebSocket after the providers are in place */}
            <WebSocketHandler />
          </UserProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
